import type { TravelPackage } from '@/types/travel'

export const samplePackages: TravelPackage[] = [
  {
    id: '1',
    name: 'Tropical Paradise Escape',
    destination: 'Maldives',
    duration: '7 Days / 6 Nights',
    price: '$2,499',
    priceValue: 2499,
    description:
      'Experience luxury in overwater bungalows with crystal-clear waters, pristine beaches, and world-class diving.',
    image: '/maldives-tropical-beach-resort.jpg',
    category: 'Luxury',
    rating: 4.9,
    maxPeople: '2-4',
  },
  {
    id: '2',
    name: 'European Heritage Tour',
    destination: 'Italy & France',
    duration: '12 Days / 11 Nights',
    price: '$3,899',
    priceValue: 3899,
    description:
      'Explore ancient ruins, Renaissance art, and culinary delights across Rome, Florence, and Paris.',
    image: '/european-cities-architecture.jpg',
    category: 'Groups',
    rating: 4.8,
    maxPeople: '2-8',
  },
  {
    id: '3',
    name: 'Mountain Adventure Trek',
    destination: 'Nepal',
    duration: '10 Days / 9 Nights',
    price: '$1,899',
    priceValue: 1899,
    description:
      'Trek through the Himalayas, visit ancient monasteries, and witness breathtaking mountain vistas.',
    image: '/himalayan-trekking.png',
    category: 'Adventure',
    rating: 4.7,
    maxPeople: '4-12',
  },
  {
    id: '4',
    name: 'Wellness Retreat & Spa',
    destination: 'Bali, Indonesia',
    duration: '8 Days / 7 Nights',
    price: '$3,299',
    priceValue: 3299,
    description:
      'Rejuvenate your mind and body with yoga, meditation, spa treatments, and healthy cuisine in paradise.',
    image: '/african-safari-wildlife.jpg',
    category: 'Wellness',
    rating: 5.0,
    maxPeople: '2-6',
  },
  {
    id: '5',
    name: 'Singles Getaway Experience',
    destination: 'Costa Rica',
    duration: '9 Days / 8 Nights',
    price: '$2,799',
    priceValue: 2799,
    description:
      'Connect with like-minded travelers, enjoy adventure activities, and explore stunning beaches and rainforests.',
    image: '/greek-islands-santorini.png',
    category: 'Singles',
    rating: 4.8,
    maxPeople: '1-1',
  },
  {
    id: '6',
    name: 'Amazon Rainforest Expedition',
    destination: 'Brazil',
    duration: '6 Days / 5 Nights',
    price: '$2,199',
    priceValue: 2199,
    description:
      "Explore the world's largest rainforest, encounter exotic wildlife, and learn from indigenous guides.",
    image: '/amazon-rainforest-jungle.jpg',
    category: 'Adventure',
    rating: 4.6,
    maxPeople: '4-10',
  },
]
