// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ldwmbwsxrktpcisqaxrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxkd21id3N4cmt0cGNpc3FheHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MDYyOTUsImV4cCI6MjA4OTE4MjI5NX0.dODVqhWKhK1tNgVPpnbsY8-0L-QXGJmDHOFd89dKaJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
